name: Moltly
options:
  xcodeVersion: '15.0'
  deploymentTarget:
    iOS: '15.0'
configs:
  - name: Debug
    type: debug
  - name: Release
    type: release
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
targets:
  Moltly:
    type: application
    platform: iOS
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xyz.moltly.app
        INFOPLIST_FILE: App/Info.plist
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
